### ISSUE TITLE
Problem with day 6 of test

### ISSUE THREAD

**Issue by VentuIlGrande** [Ax6/Fast-F1#6]
If I try to execute the code of the day 6 it gives me this error, only this day though

Pre-Season Test 2 Practice 3
C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\core.py:133: UserWarning: Ergast api not supported for testing.
  warnings.warn("Ergast api not supported for testing.")
INFO:root:Loading Pre-Season Test 2 Practice 3
INFO:root:Getting summary...
INFO:root:Formatting summary...
Traceback (most recent call last):
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\core.py", line 322, in _load_summary
    result = pd.merge_asof(d1, d2, on='Time', by='Driver')
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\reshape\merge.py", line 541, in merge_asof
    return op.get_result()
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\reshape\merge.py", line 1461, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\reshape\merge.py", line 862, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\reshape\merge.py", line 1726, in _get_join_indexers
    raise ValueError(msg_sorted.format(side="left"))
ValueError: left keys must be sorted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    laps = test.load_laps()
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\utils.py", line 58, in decorator
    laps = func(*args, **kwargs)
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\core.py", line 281, in load_laps
    self.laps = Laps(self._load_summary())
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\core.py", line 339, in _load_summary
    result = pd.read_csv(file_path)
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 673, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File C:\Users\LVent\AppData\Local\Programs\Python\Python38\lib\site-packages\fastf1\bottas_test_2020_02_28.csv does not exist: 'C:\\Users\\LVent\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\fastf1\\bottas_test_2020_02_28.csv'

**Comment by Ax6** [comment]
It looks like the library is not finding the bottas patch of day 6. I forgot to add it in a previous commit https://github.com/Ax6/Fast-F1/issues/4#issue-572917777.
Is your fast f1 up to date? If not run again` pip install git+https://github.com/Ax6/fast-f1.git`

**Comment by VentuIlGrande** [comment]
I ran the command again but still the same problem

**Comment by Ax6** [comment]
The missing file is in the latest version. Make sure that the library is updating correctly. If it happens again can you provide the output of the update command?

**Comment by VentuIlGrande** [comment]
I manually added the csv files and it works now
