### ISSUE TITLE
Error getting Testing day 3 laps with latest version

### ISSUE THREAD

**Issue by Xwang1976** [Ax6/Fast-F1#8]
day3=ff1.get_session(2020, 'testing' , 3 )
Pre-Season Test 1 Practice 3
/home/andreak/.local/lib/python3.8/site-packages/fastf1/core.py:150: UserWarning: Ergast api not supported for testing.
  warnings.warn("Ergast api not supported for testing.")

day3_laps=day3.load_laps()
INFO:root:Loading Pre-Season Test 1 Practice 3
INFO:root:Getting summary...
INFO:root:Formatting summary...
Traceback (most recent call last):

  File "/home/andreak/.local/lib/python3.8/site-packages/fastf1/core.py", line 354, in _load_summary
    result = pd.merge_asof(d1, d2, on='Time', by='Driver')

  File "/usr/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 541, in merge_asof
    return op.get_result()

  File "/usr/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1461, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()

  File "/usr/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 862, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()

  File "/usr/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1726, in _get_join_indexers
    raise ValueError(msg_sorted.format(side="left"))

ValueError: left keys must be sorted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-4-8e0f09028f5f>", line 1, in <module>
    day3_laps=day3.load_laps()

  File "/home/andreak/.local/lib/python3.8/site-packages/fastf1/utils.py", line 105, in decorator
    laps = func(*args, **kwargs)

  File "/home/andreak/.local/lib/python3.8/site-packages/fastf1/core.py", line 313, in load_laps
    self.laps = Laps(self._load_summary())

  File "/home/andreak/.local/lib/python3.8/site-packages/fastf1/core.py", line 371, in _load_summary
    result = pd.read_csv(file_path)

  File "/usr/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)

  File "/usr/lib/python3.8/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)

  File "/usr/lib/python3.8/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)

  File "/usr/lib/python3.8/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)

  File "pandas/_libs/parsers.pyx", line 859, in pandas._libs.parsers.TextReader.read

  File "pandas/_libs/parsers.pyx", line 874, in pandas._libs.parsers.TextReader._read_low_memory

  File "pandas/_libs/parsers.pyx", line 928, in pandas._libs.parsers.TextReader._read_rows

  File "pandas/_libs/parsers.pyx", line 915, in pandas._libs.parsers.TextReader._tokenize_rows

  File "pandas/_libs/parsers.pyx", line 2070, in pandas._libs.parsers.raise_parser_error

ParserError: Error tokenizing data. C error: Expected 1 fields in line 49, saw 2

**Comment by Xwang1976** [comment]
Same or similar issue with day 6:

day3=ff1.get_session(2020, 'testing' , 6 )
Pre-Season Test 2 Practice 3
/home/andreak/.local/lib/python3.8/site-packages/fastf1/core.py:150: UserWarning: Ergast api not supported for testing.
  warnings.warn("Ergast api not supported for testing.")

day3_laps=day3.load_laps()
INFO:root:Loading Pre-Season Test 2 Practice 3
INFO:root:Getting summary...
INFO:root:Formatting summary...
Traceback (most recent call last):

  File "/home/andreak/.local/lib/python3.8/site-packages/fastf1/core.py", line 354, in _load_summary
    result = pd.merge_asof(d1, d2, on='Time', by='Driver')

  File "/usr/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 541, in merge_asof
    return op.get_result()

  File "/usr/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1461, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()

  File "/usr/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 862, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()

  File "/usr/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1726, in _get_join_indexers
    raise ValueError(msg_sorted.format(side="left"))

ValueError: left keys must be sorted


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-10-8e0f09028f5f>", line 1, in <module>
    day3_laps=day3.load_laps()

  File "/home/andreak/.local/lib/python3.8/site-packages/fastf1/utils.py", line 105, in decorator
    laps = func(*args, **kwargs)

  File "/home/andreak/.local/lib/python3.8/site-packages/fastf1/core.py", line 313, in load_laps
    self.laps = Laps(self._load_summary())

  File "/home/andreak/.local/lib/python3.8/site-packages/fastf1/core.py", line 371, in _load_summary
    result = pd.read_csv(file_path)

  File "/usr/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)

  File "/usr/lib/python3.8/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)

  File "/usr/lib/python3.8/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)

  File "/usr/lib/python3.8/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)

  File "pandas/_libs/parsers.pyx", line 859, in pandas._libs.parsers.TextReader.read

  File "pandas/_libs/parsers.pyx", line 874, in pandas._libs.parsers.TextReader._read_low_memory

  File "pandas/_libs/parsers.pyx", line 928, in pandas._libs.parsers.TextReader._read_rows

  File "pandas/_libs/parsers.pyx", line 915, in pandas._libs.parsers.TextReader._tokenize_rows

  File "pandas/_libs/parsers.pyx", line 2070, in pandas._libs.parsers.raise_parser_error

ParserError: Error tokenizing data. C error: Expected 1 fields in line 49, saw 2

**Comment by Ax6** [comment]
It could be something related with the .csv files. Try to do the following:

1 - cd to your working directory
2 - run `git clone https://github.com/Ax6/Fast-F1 lib_test`
3 - `cd lib_test`
4 - Replace the setup.py file with the one I attached to the comment
5 - run `python setup.py install`

And see if this solved the issue
[setup_test.zip](https://github.com/Ax6/Fast-F1/files/4281762/setup_test.zip)

**Comment by Xwang1976** [comment]
I have done as you said and now it works.
Next time I have to upgrade should I use this procedure or can I upgrade with pip?

**Comment by Ax6** [comment]
Great! I will push the updated setup file on the repository. Next time you will be able to update just using pip.
